-- Medidas que usan las tablas: presupuesto_col (presupuesto) y ejecucion (ejecución real)

Monto Presupuestado = 
    SUM ( presupuesto_col[Monto Presupuestado] )

Monto Ejecutado = 
    SUM ( ejecucion[Monto Ejecutado] )

Variación = 
    [Monto Ejecutado] - [Monto Presupuestado]

Variación % = 
    DIVIDE([Variación], [Monto Presupuestado])

-- Versiones anuales (ignoran el filtro de mes, conservan año/equipo/tipo)

Monto Presupuestado (Año) =
    CALCULATE([Monto Presupuestado], ALL(DimPeriodo[Periodo]))

Monto Ejecutado (Año) =
    CALCULATE([Monto Ejecutado], ALL(DimPeriodo[Periodo]))

Variación (Año) = 
    [Monto Ejecutado (Año)] - [Monto Presupuestado (Año)]

Variación % (Año) = 
    DIVIDE( [Variación (Año)], [Monto Presupuestado (Año)] )